name: GitlabSync

on:
  - push
  - delete

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: wangchucheng/git-repo-sync@v0.1.0
      with:
        target-url: https://gitlab.nccr-automation.ch/roland.schwan/evanqp.git
        target-username: roland.schwan
        target-token: ${{ secrets.TARGET_TOKEN }}
